name: check-auth
run-name: Make sure the access and refresh tokens are up-to-date
on: [workflow_call]  # allow this workflow to be called from other workflows
jobs:
 refresh-tokens:
    runs-on: ubuntu-latest
    outputs:
      tokens-updated: ${{ steps.update-config.outputs.tokens-updated }}
    env:
      SF_API_CLIENT_ID: "${{ secrets.SF_API_CLIENT_ID }}"
      SF_API_SECRET: "${{ secrets.SF_API_SECRET }}"
    steps:
      - name: Testing
        id: update-config
        run: "echo test"
      - name: Load Silverfin config file from secrets
        run: |
          mkdir -p $HOME/.silverfin/
          touch $HOME/.silverfin/config.json
          echo '${{ secrets.CONFIG_JSON }}' > $HOME/.silverfin/config.json
      - name: Refresh token
        run: |
          node ./node_modules/silverfin-cli/bin/cli.js config --set-firm 13827
          node ./node_modules/silverfin-cli/bin/cli.js config --refresh-token
      - name: Prepare CONFIG_JSON to be stored as a secret
        if: always()
        run: |
          CONFIG_JSON=$(cat $HOME/.silverfin/config.json | tr -d '\n')
          echo "CONFIG_JSON=${CONFIG_JSON}" >> $GITHUB_ENV
      - name: Store CONFIG_JSON as secret
        uses: gliech/create-github-secret-action@v1
        if: always()
        with:
          name: CONFIG_JSON
          value: "${{ env.CONFIG_JSON }}"
          pa_token: ${{ secrets.REPO_ACCESS_TOKEN }}