name: refresh-api-tokens
run-name: Make sure the access and refresh tokens are up-to-date
on: [workflow_call]  # allow this workflow to be called from other workflows
jobs:
 refresh-auth:
    runs-on: ubuntu-latest
    outputs:
      tokens-updated: ${{ steps.update-config.outputs.tokens-updated }}
    env:
      SF_API_CLIENT_ID: "${{ secrets.SF_API_CLIENT_ID }}"
      SF_API_SECRET: "${{ secrets.SF_API_SECRET }}"
    steps:
      - name: Labeled to functional review
        id: update-config
        run: "echo test"